services:
  app:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SELENIUM_URL=http://selenium:4444
    volumes:
      - ./artifacts:/usr/src/app/artifacts
    depends_on:
      selenium:
        condition: service_healthy

  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    restart: unless-stopped
    shm_size: 2g
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
    ports:
      - "4444:4444"
      # - "7900:7900"   # (optional) noVNC viewer
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:4444/status | grep -q 'ready'"]
      interval: 5s
      timeout: 3s
      retries: 30

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
